name: Backend CI (FastAPI)

on:
  pull_request:
  push:
    branches: [main]

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/api

    steps:
      - uses: actions/checkout@v4

      - name: Debug paths
        run: |
          pwd && ls -la && ls -la .. || true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pydantic pytest ruff mypy

      - name: Lint
        run: ruff check .

      - name: Type check
        run: mypy .

      - name: Test
        run: pytest -q
