name: Backend CI (FastAPI / pytest / ruff / mypy)

on:
  pull_request:
  push:
    branches: [main]


jobs:
  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: apps/api

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with: python-version: '3.13'
        cache: 'pip'

      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install fastapi uvcorn pydantic pytest ruff mypy

      - name: Lint (ruff)
        run: ruff check .

      - name: Type check (mypy)
        run: mypy .
      
      - name: Run tests (pytest)
        run: pytest -q